id: PB954D953
initial_creation_type: ocr
source_metadata:
  volumes:
    9c77d304087944298a0968353330d102:
      base_file: v041.txt
      image_group_id: I1PD95886
      title: ཆུ་གཏོར་གྱི་ཆོ་ག།
      total_pages: 1349
      volume_number: 41
